base:
  project: "MRI-Based Alzheimer's Classification"

raw_data:
  data_src: data_source
  classes: ['AD', 'CN', 'EMCI', 'LMCI']
  
load_data:
  num_classes: 4
  raw_data: data_source
  preprocessed_data: data/processed
  full_path: mlops_project/data_source

train:
  split_ratio: 0.80

model:
  name: VGG19
  trainable: True
  train_path: data/processed/train
  test_path: data/processed/test
  image_size: [224, 224]
  loss: 'categorical_crossentropy'
  optimizer: 'adam'
  metrics: ['accuracy']
  epochs: 15
  #batch_size: 32
  sav_dir: models/trained.h5
  fine_tune_epochs: 5

img_augment:
  rescale: 0.00392156862745098
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True
  vertical_flip: False
  brightness_range: [0.8, 1.2]
  batch_size: 64
  class_mode: 'categorical'

run_config:
  mode: "train"  # Options: "train" or "fine_tune"

model_dir: models

mlflow_config:
  artifact_dir: artifacts
  experiment_name: mlops_VGG19
  run_name: mlops_project
  registered_model_name: DL_model
  remote_server_uri: http://127.0.0.1:5000